
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: backend

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: laravel_tags
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: branches
      run: git branch
    - name: checkout
      run: git checkout backend
    - name: branches
      run: git branch
    - name: pwd
      run: pwd
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "CREATE DATABASE eportfolio"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
    - name: Build with Maven
      run: mvn -B package --file /home/runner/work/ci/ci/demo/pom.xml
